#!/usr/bin/env bash
#
# Refresh repo-root examples/ from dogfood per-function manifests (canonical
# copy). Run after changing docs/demos/per-function/*.docgen.yaml or from
# _full-reset-regenerate.sh so published examples never drift from dogfood.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export ROOT
SRC_MANIFEST="$ROOT/docs/demos/per-function/lesson-compile.docgen.yaml"
DST_YAML="$ROOT/examples/lesson_compile.docgen.yaml"
DST_PY="$ROOT/examples/sample_test.py"

if [ ! -f "$SRC_MANIFEST" ]; then
  echo "[seed-examples] missing $SRC_MANIFEST" >&2
  exit 2
fi

mkdir -p "$ROOT/examples"

echo "=== [$(date +%H:%M:%S)] seed-examples: copy manifest -> $DST_YAML ==="
{
  printf '%s\n' \
    '# Synced from docs/demos/per-function/lesson-compile.docgen.yaml' \
    '# Regenerate: docs/demos/_seed-examples.sh (or _full-reset-regenerate.sh)' \
    ''
  cat "$SRC_MANIFEST"
} > "$DST_YAML"

echo "=== [$(date +%H:%M:%S)] seed-examples: emit @pytest.mark.docgen -> $DST_PY ==="
python3 <<'PY'
from __future__ import annotations

import os
from pathlib import Path

import yaml

ROOT = Path(os.environ["ROOT"])
yaml_path = ROOT / "examples" / "lesson_compile.docgen.yaml"
out_path = ROOT / "examples" / "sample_test.py"
raw = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}

if not isinstance(raw, dict):
    raise SystemExit("manifest root must be a mapping")


def to_py(obj: object) -> str:
    if isinstance(obj, str):
        return repr(obj)
    if isinstance(obj, bool):
        return "True" if obj else "False"
    if obj is None:
        return "None"
    if isinstance(obj, (int, float)):
        return repr(obj)
    if isinstance(obj, list):
        inner = ", ".join(to_py(x) for x in obj)
        return f"[{inner}]"
    if isinstance(obj, dict):
        pairs: list[str] = []
        for k in sorted(obj.keys(), key=lambda s: str(s)):
            pairs.append(f"{k!r}: {to_py(obj[k])}")
        return "{" + ", ".join(pairs) + "}"
    raise TypeError(f"unsupported {type(obj)}")


def kwargs_lines(d: dict) -> str:
    lines: list[str] = []
    for k in sorted(d.keys(), key=str):
        lines.append(f"    {k}={to_py(d[k])},")
    return "\n".join(lines)


header = '''\
"""Sample test: @pytest.mark.docgen(...) mirrors examples/lesson_compile.docgen.yaml.

Generated by docs/demos/_seed-examples.sh — edit docs/demos/per-function/lesson-compile.docgen.yaml
and re-run the seed script.

The marker is read statically by `docgen demo-function --manifest <file>::<test>` via `ast`
(no import / no exec). Triple-quoted text below intentionally mentions
``pytest.mark.docgen`` to verify the AST-based loader is not fooled by docstrings
(regression guard for F7).
"""

import pytest


'''
decorator = "@pytest.mark.docgen(\n" + kwargs_lines(raw) + "\n)"
body = f"{decorator}\ndef test_lesson_compile():\n    pass\n"
out_path.write_text(header + body, encoding="utf-8")
PY

echo "=== [$(date +%H:%M:%S)] seed-examples done ==="
