"""Manim scene pipeline support: YAML specs, bootstrap, prompts, and injection.

`manim_scene_generation` in ``docgen.yaml`` (see :func:`merged_scene_generation_settings`)
supplies model settings, hints, and context paths for **YAML** scene specs.
This module provides timing enrichment, bootstrap + marker injection for
``animations/scenes.py``, LLM transport (:func:`call_llm`), and
:class:`lint_generated_block` used after deterministic compilation.

Diagram pacing is **declarative** only: ``docgen scene-spec-generate`` /
``docgen scene-compile`` emit marker-bounded classes from ``*.scene.yaml``.
Hand-edit Python only **outside** generated blocks when necessary.
"""

from __future__ import annotations

import ast
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from docgen.config import Config

from docgen.validate import lint_manim_timing_stub_antipattern

_TITLE_DOWN_OVERLAP_RE = re.compile(r"\.next_to\(\s*title\s*,\s*DOWN\b")
_SHIFT_LEFT_RE = re.compile(r"\.shift\(\s*LEFT\s*\*")
_SHIFT_RIGHT_RE = re.compile(r"\.shift\(\s*RIGHT\s*\*")


def lint_manim_title_down_row_collision_risk(code: str) -> list[str]:
    """Flag a layout anti-pattern that stacks a wide box over flanking side boxes.

    When two mobjects are placed with ``.shift(LEFT * n)`` / ``.shift(RIGHT * n)``
    and another uses ``.next_to(title, DOWN, ...)`` only, their bounding boxes
    often collide on the same horizontal band. Prefer ``VGroup(...).arrange(RIGHT)``
    rows chained with ``.next_to(row, DOWN)`` instead.
    """
    if (
        _SHIFT_LEFT_RE.search(code)
        and _SHIFT_RIGHT_RE.search(code)
        and _TITLE_DOWN_OVERLAP_RE.search(code)
    ):
        # Init-style scenes may use ReplacementTransform with a title-anchored box;
        # do not block those wholesale.
        if "ReplacementTransform" in code:
            return []
        return [
            "layout: pairing `.shift(LEFT * …)` + `.shift(RIGHT * …)` with "
            "`.next_to(title, DOWN, …)` usually overlaps a centered box onto the "
            "side boxes; build `VGroup(left, right).arrange(RIGHT, buff=…)`, "
            "`row.next_to(title, DOWN, buff=…)`, then chain further rows with "
            "`.next_to(row, DOWN, buff=…)` only."
        ]
    return []

DEFAULT_MODEL = "gpt-4o"
DEFAULT_TEMPERATURE = 0.4
DEFAULT_MAX_CONTEXT_BYTES = 80_000


# Stable marker contract used by `_inject_or_replace`. Must remain stable:
# changing these strings breaks idempotent regeneration in existing repos.
MARKER_BEGIN_FMT = "# ── BEGIN GENERATED SCENE: {seg_id} ({class_name}) ──"
MARKER_END_FMT = "# ── END GENERATED SCENE: {seg_id} ──"


# Bootstrap template written to ``scenes.py`` when the file is missing or
# lacks the helpers we depend on. This block is the canonical helper definition;
# generated `_TimedScene` classes assume these helpers (`_box`, `wait_word`,
# `wait_segment`, color constants) are present at the top of the bundle's
# `animations/scenes.py`.
BOOTSTRAP_HEADER = '''"""
Manim scenes for docgen demo videos.

Pacing is driven by timing.json (generated by ``docgen timestamps``).
Scene classes below this header are injected by ``docgen scene-spec-generate``
/ ``docgen scene-compile`` between marker blocks; helpers and palette are
hand-maintained.

Frame: 14.22 wide x 8 tall.  Coordinates x in [-7.11, 7.11], y in [-4, 4].
Keep **all** mobjects inside this rectangle: wide `arrange(RIGHT)` rows and long
`next_to(..., DOWN)` chains both clip in 720p unless bounded (see `_row_fit`,
`_column_fit_below_title`).
"""

from __future__ import annotations

import json
from pathlib import Path

from manim import *  # noqa: F401,F403

# ── Palette ──────────────────────────────────────────────────────────
C_BG = "#1e1e2e"
C_ACCENT = "#667eea"
C_GREEN = "#42b883"
C_ORANGE = "#f9a825"
C_BLUE = "#2979ff"
C_RED = "#ff5252"
C_TEAL = "#26c6da"
C_PURPLE = "#ce93d8"
C_WHITE = "#cdd6f4"

# Layout: default Manim 16:9 frame ~14.22 x 8. Leave margin so nothing touches edges.
SAFE_CONTENT_WIDTH = 12.85
SAFE_BOTTOM_Y = -3.55


def _row_fit(*parts, buff=0.38):
    """Single horizontal row scaled to fit ``SAFE_CONTENT_WIDTH`` (prevents off-screen RIGHT)."""
    row = VGroup(*parts).arrange(RIGHT, buff=buff)
    if row.width > SAFE_CONTENT_WIDTH:
        row.scale(SAFE_CONTENT_WIDTH / row.width)
    return row


def _column_fit_below_title(title: Mobject, column: Mobject, buff=0.55):
    """Stack / column placed under ``title``; uniform scale if bottom would fall below ``SAFE_BOTTOM_Y``.

    Also enforces a hard non-overlap with the title's bounding box: after
    ``next_to``, if the column's top would still be above ``title.bottom - buff``
    (e.g. because the caller scaled the title via an ``.animate`` chain that
    Manim resolves with a different bbox than expected), the column is shifted
    DOWN by the missing clearance. This makes title-overlap impossible regardless
    of how the title was last transformed.
    """
    column.next_to(title, DOWN, buff=buff)
    required_top = title.get_bottom()[1] - buff
    actual_top = column.get_top()[1]
    if actual_top > required_top:
        column.shift(DOWN * (actual_top - required_top))
    bottom_y = column.get_bottom()[1]
    if bottom_y < SAFE_BOTTOM_Y:
        top_y = column.get_top()[1]
        available = max(top_y - SAFE_BOTTOM_Y, 0.25)
        if column.height > 1e-6 and available < column.height:
            column.scale(available / column.height, about_point=column.get_top())
    return column


def _load_timing(segment_key: str) -> list[dict]:
    """Return Whisper segments from timing.json for a given segment key."""
    timing_path = Path(__file__).parent / "timing.json"
    if not timing_path.exists():
        return []
    data = json.loads(timing_path.read_text())
    return data.get(segment_key, {}).get("segments", [])


def _load_timing_words(segment_key: str) -> list[dict]:
    """Return Whisper word-level entries from timing.json (``words`` list)."""
    timing_path = Path(__file__).parent / "timing.json"
    if not timing_path.exists():
        return []
    data = json.loads(timing_path.read_text())
    block = data.get(segment_key) or {}
    words = block.get("words")
    return list(words) if isinstance(words, list) else []


def _box(label, color, w=2.2, h=0.75, fs=18):
    r = RoundedRectangle(
        corner_radius=0.15, width=w, height=h,
        stroke_color=color, fill_color=color, fill_opacity=0.2,
    )
    t = Text(str(label), font_size=fs, color=color)
    inner_w = max(w - 0.25, 0.35)
    inner_h = max(h - 0.2, 0.35)
    if t.width > inner_w:
        t.scale(inner_w / t.width)
    if t.height > inner_h:
        t.scale(inner_h / t.height)
    t.move_to(r.get_center())
    return VGroup(r, t)


def _arrow(start, end, color="#cdd6f4"):
    return Arrow(start, end, color=color, stroke_width=2, buff=0.15, max_tip_length_to_length_ratio=0.12)


class _TimedScene(Scene):
    """Base with a clock that tracks elapsed scene time."""

    def setup(self):
        self._clock = 0.0

    def timed_play(self, *animations, run_time=1.0, **kwargs):
        self.play(*animations, run_time=run_time, **kwargs)
        self._clock += run_time

    def wait_until(self, target: float):
        gap = target - self._clock
        if gap > 0.05:
            self.wait(gap)
            self._clock += gap

    def timed_wait(self, duration: float):
        if duration > 0.05:
            self.wait(duration)
            self._clock += duration

    def wait_until_word(self, words, index: int):
        """Wait until Whisper ``words[index]['start']`` (no-op if index invalid)."""
        if not words or index < 0 or index >= len(words):
            return
        try:
            t = float(words[index].get("start", 0.0))
        except (TypeError, ValueError):
            return
        self.wait_until(t)

    def pace_to_beat(self, segments, beat_index, num_beats, segment_indices=None):
        """Wait until the Whisper segment start for this story beat.

        If ``segment_indices`` is a sequence of Whisper **segment** indices (one per beat),
        use ``segment_indices[beat_index]`` as the segment row index. Otherwise spread
        beats evenly across segment indices (legacy behaviour).
        """
        if not segments or num_beats <= 0:
            return
        n = len(segments)
        if segment_indices is not None:
            if beat_index < 0 or beat_index >= num_beats:
                return
            if beat_index >= len(segment_indices):
                return
            j = int(segment_indices[beat_index])
            j = max(0, min(n - 1, j))
            self.wait_until(float(segments[j].get("start", 0.0)))
            return
        if n == 1:
            self.wait_until(float(segments[0].get("start", 0.0)))
            return
        si = min(int(round(beat_index * (n - 1) / max(num_beats - 1, 1))), n - 1)
        self.wait_until(float(segments[si].get("start", 0.0)))

    def paced_reveal(self, segments, mobjects, segment_indices, run_time=0.55):
        """Reveal each mobject at its paired Whisper segment start.

        For each ``mobjects[k]`` paired with ``segment_indices[k]``: wait until that
        Whisper segment's ``start`` (via ``pace_to_beat``) and play ``FadeIn(mobject)``
        with the mobject already laid out at its final position. Caller MUST NOT
        pre-set opacity to 0 on the mobjects -- ``FadeIn`` animates 0 -> the
        mobject's current opacity, so an invisible target stays invisible.

        If there are more ``mobjects`` than ``segment_indices`` the extras are spread
        evenly across the remaining Whisper segments. If ``segments`` is empty the
        mobjects fade in immediately, in order, with no pacing.
        """
        if not mobjects:
            return
        n_m = len(mobjects)
        indices = list(segment_indices) if segment_indices is not None else []
        if not segments:
            for m in mobjects:
                self.timed_play(FadeIn(m), run_time=run_time)
            return
        for k, m in enumerate(mobjects):
            if k < len(indices):
                self.pace_to_beat(segments, k, len(indices), indices)
            else:
                self.pace_to_beat(segments, k, n_m)
            self.timed_play(FadeIn(m), run_time=run_time)
'''


REQUIRED_HELPERS = ("_TimedScene", "_box", "_arrow", "_load_timing", "_load_timing_words")


class SceneGenerationError(RuntimeError):
    """Raised when the LLM output is unusable (no class, wrong name, parse fail)."""


@dataclass(frozen=True)
class SceneGenerationSettings:
    model: str
    temperature: float
    max_context_bytes: int
    system_prompt: str  # optional ``manim_scene_generation.system_prompt`` (unused by scene-spec path)
    hints: list[str]
    context_paths: list[str]
    context_globs: list[str]
    class_name: str | None  # set when YAML provides ``segments.<id>.class_name``


def _as_str_list(x: Any) -> list[str]:
    if x is None:
        return []
    if isinstance(x, str):
        return [x] if x.strip() else []
    if isinstance(x, list):
        return [str(i).strip() for i in x if str(i).strip()]
    return []


def merged_scene_generation_settings(cfg: "Config", seg_id: str) -> SceneGenerationSettings:
    """Merge ``manim_scene_generation`` defaults with optional per-segment overrides.

    Layout::

        manim_scene_generation:
          model: gpt-4o
          temperature: 0.4
          max_context_bytes: 80000
          max_whisper_segments_in_prompt: 0
          max_whisper_words_in_prompt: 0
          max_whisper_segment_text_chars: 200
          default_visual_beats: null
          system_prompt: <override>
          hints: [...]
          context:
            paths: [...]
            globs: [...]
          segments:
            "<id>":
              class_name: <ClassName>Scene
              visual_beats: 10
              pace_segment_indices: [0, 2, 5, 9]
              hints: [...]
              context:
                paths: [...]
                globs: [...]

    ``max_whisper_segments_in_prompt: 0`` sends every Whisper **segment** row to the LLM;
    ``max_whisper_words_in_prompt: 0`` sends every **word** token (when present). Positive
    caps trim prompt size. ``pace_segment_indices`` (optional) plugs each
    visual beat to a segment index; otherwise ``visual_beats`` or ``default_visual_beats``
    selects an evenly spread schedule.

    All hints are project-owner authored (visual copy and layout only); they must not
    carry Whisper indices or clock times. Pacing plugs (`pace_segment_indices`,
    `visual_beats`) are not merged from hint files; set them in committed bundle
    ``docgen.yaml`` when needed, or rely on TIMING JSON / auto tables in the spec prompt.
    """
    root = cfg.raw.get("manim_scene_generation")
    if not isinstance(root, dict):
        root = {}
    seg_block = root.get("segments")
    seg: dict[str, Any] = {}
    if isinstance(seg_block, dict):
        raw_seg = seg_block.get(seg_id)
        if isinstance(raw_seg, dict):
            seg = raw_seg

    ctx_root = root.get("context") if isinstance(root.get("context"), dict) else {}
    ctx_seg = seg.get("context") if isinstance(seg.get("context"), dict) else {}
    paths = _as_str_list(ctx_root.get("paths")) + _as_str_list(ctx_seg.get("paths"))
    globs = _as_str_list(ctx_root.get("globs")) + _as_str_list(ctx_seg.get("globs"))

    hints = _as_str_list(root.get("hints")) + _as_str_list(seg.get("hints"))

    model = str(root.get("model") or DEFAULT_MODEL).strip() or DEFAULT_MODEL
    temperature = float(root.get("temperature", DEFAULT_TEMPERATURE))
    max_bytes = int(root.get("max_context_bytes", DEFAULT_MAX_CONTEXT_BYTES))

    sys_override = str(root.get("system_prompt", "")).strip()
    seg_sys = str(seg.get("system_prompt", "")).strip()
    if seg_sys:
        system_prompt = seg_sys
    elif sys_override:
        system_prompt = sys_override
    else:
        system_prompt = ""

    cls_name = str(seg.get("class_name", "")).strip() or None

    return SceneGenerationSettings(
        model=model,
        temperature=temperature,
        max_context_bytes=max_bytes,
        system_prompt=system_prompt,
        hints=hints,
        context_paths=paths,
        context_globs=globs,
        class_name=cls_name,
    )


def manim_scene_generation_root(cfg: "Config") -> dict[str, Any]:
    r = cfg.raw.get("manim_scene_generation")
    return r if isinstance(r, dict) else {}


def manim_scene_generation_segment_block(cfg: "Config", seg_id: str) -> dict[str, Any]:
    root = manim_scene_generation_root(cfg)
    segs = root.get("segments")
    if not isinstance(segs, dict):
        return {}
    sid = str(seg_id).strip()
    for key in (sid, int(sid) if sid.isdigit() else None):
        if key is None:
            continue
        raw = segs.get(key)
        if isinstance(raw, dict):
            return raw
    return {}


def _parse_int_sequence(x: Any) -> list[int] | None:
    if x is None:
        return None
    if isinstance(x, (list, tuple)):
        out: list[int] = []
        for v in x:
            try:
                out.append(int(v))
            except (TypeError, ValueError):
                return None
        return out
    return None


def even_spread_segment_indices(num_beats: int, num_segments: int) -> list[int]:
    """Map each beat 0..num_beats-1 to a Whisper segment index (inclusive ends)."""
    if num_beats <= 0 or num_segments <= 0:
        return []
    if num_segments == 1:
        return [0] * num_beats
    return [
        min(int(round(i * (num_segments - 1) / max(num_beats - 1, 1))), num_segments - 1)
        for i in range(num_beats)
    ]


def resolve_pace_segment_indices(
    *,
    num_segments: int,
    seg_block: dict[str, Any],
    root: dict[str, Any],
) -> tuple[list[int], str]:
    """Return (one Whisper segment index per visual beat, provenance string)."""
    if num_segments <= 0:
        return [], "no Whisper segments"
    explicit = _parse_int_sequence(seg_block.get("pace_segment_indices"))
    if explicit:
        clamped = [max(0, min(num_segments - 1, int(i))) for i in explicit]
        return clamped, "manim_scene_generation.segments.<id>.pace_segment_indices"

    raw_beats = seg_block.get("visual_beats", root.get("default_visual_beats"))
    if raw_beats is not None:
        try:
            nb = max(1, int(raw_beats))
        except (TypeError, ValueError):
            nb = min(12, max(4, max(1, (num_segments + 1) // 2)))
    else:
        nb = min(12, max(4, max(1, (num_segments + 1) // 2)))
    nb = min(nb, 48)
    return even_spread_segment_indices(nb, num_segments), "auto (set visual_beats or pace_segment_indices to override)"


def prepare_whisper_segments_for_prompt(
    segments: list[dict],
    *,
    max_segments: int,
    max_text_chars: int,
) -> list[dict]:
    """JSON-safe rows for the LLM; preserves global whisper_index for alignment with pacing."""
    out: list[dict] = []
    cap = len(segments) if max_segments <= 0 else min(len(segments), max_segments)
    for global_i in range(cap):
        s = segments[global_i]
        text = str(s.get("text", "")).strip().replace("\n", " ")
        if max_text_chars > 0 and len(text) > max_text_chars:
            text = text[: max_text_chars - 3] + "..."
        out.append(
            {
                "whisper_index": global_i,
                "start": float(s.get("start", 0.0)),
                "end": float(s.get("end", 0.0)),
                "text": text,
            }
        )
    return out


def format_pacing_schedule_markdown(segments: list[dict], pace_indices: list[int]) -> str:
    lines = [
        "| beat_i | whisper_index | start_sec | text_preview |",
        "| --- | --- | --- | --- |",
    ]
    for i, seg_i in enumerate(pace_indices):
        seg_i = max(0, min(len(segments) - 1, int(seg_i)))
        s = segments[seg_i]
        text = str(s.get("text", "")).strip().replace("|", "/").replace("\n", " ")[:72]
        lines.append(
            f"| {i} | {seg_i} | {float(s.get('start', 0.0)):.3f} | {text} |"
        )
    return "\n".join(lines)


def _load_timing_words_from_cfg(cfg: "Config", seg_name: str) -> list[dict]:
    """Return the ``words`` list from ``animations/timing.json`` for ``seg_name``."""
    timing_path = cfg.animations_dir / "timing.json"
    if not timing_path.is_file():
        return []
    try:
        data = json.loads(timing_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    block = data.get(seg_name)
    if not isinstance(block, dict):
        return []
    words = block.get("words")
    return list(words) if isinstance(words, list) else []


def prepare_whisper_words_for_prompt(
    words: list[dict],
    *,
    max_words: int,
    max_text_chars: int,
) -> list[dict]:
    """JSON-safe word rows for the LLM; preserves global ``word_index`` for YAML ``wait_word``."""
    out: list[dict] = []
    cap = len(words) if max_words <= 0 else min(len(words), max_words)
    for global_i in range(cap):
        w = words[global_i]
        text = str(w.get("word", w.get("text", ""))).strip().replace("\n", " ")
        if max_text_chars > 0 and len(text) > max_text_chars:
            text = text[: max_text_chars - 3] + "..."
        out.append(
            {
                "word_index": global_i,
                "start": float(w.get("start", 0.0)),
                "end": float(w.get("end", 0.0)),
                "word": text,
            }
        )
    return out


def build_timing_enrichment_for_prompt(
    cfg: "Config",
    seg_id: str,
    seg_name: str,
    whisper_segments: list[dict],
) -> str:
    """Whisper timing for the scene-spec LLM: word stream first (`wait_word`), else segments (`wait_segment`)."""
    root = manim_scene_generation_root(cfg)
    seg_block = manim_scene_generation_segment_block(cfg, seg_id)
    max_seg = int(root.get("max_whisper_segments_in_prompt", 0) or 0)
    max_words = int(root.get("max_whisper_words_in_prompt", 0) or 0)
    try:
        max_chars = int(root.get("max_whisper_segment_text_chars", 200) or 200)
    except (TypeError, ValueError):
        max_chars = 200
    max_chars = max(0, max_chars)

    whisper_words = _load_timing_words_from_cfg(cfg, seg_name)
    n_words_total = len(whisper_words)
    n_seg_total = len(whisper_segments)

    parts: list[str] = []
    parts.append(
        f"--- TIMING STEM — `{seg_name!r}` must match timing.json and `audio/{seg_name}.mp3` ---"
    )

    if not whisper_segments and not whisper_words:
        parts.append(
            "# timing.json has no segments or words for this stem yet. "
            "Use explicit `run_time` only; omit `wait_word` / `wait_segment` until after `docgen timestamps`."
        )
        return "\n".join(parts)

    if whisper_words:
        compact_w = prepare_whisper_words_for_prompt(
            whisper_words,
            max_words=max_words,
            max_text_chars=max_chars,
        )
        parts.append("--- WORD TIMING (primary; YAML `wait_word` = `word_index` from this JSON) ---")
        parts.append(
            "# Set `wait_word: N` on a row to wait until token N's `start` (seconds), matching timing.json "
            "`words[N]`. Choose N by scanning for the **first** `word` whose text aligns with that row's "
            "box labels (distinctive words). One timing field per row; the toolchain may refine indices from labels."
        )
        parts.append(json.dumps(compact_w, indent=2, ensure_ascii=False))
        if max_words > 0 and n_words_total > max_words:
            parts.append(
                f"# Note: listed {len(compact_w)} of {n_words_total} tokens "
                f"(manim_scene_generation.max_whisper_words_in_prompt={max_words}; 0 = all). "
                "`word_index` is the index into the full `words` array in timing.json."
            )
        else:
            parts.append(f"# Full word token list for this stem ({n_words_total} tokens).")

        if whisper_segments:
            compact_seg = prepare_whisper_segments_for_prompt(
                whisper_segments,
                max_segments=max_seg,
                max_text_chars=max_chars,
            )
            parts.append("")
            parts.append("--- COARSE SEGMENTS (optional context; pacing uses `wait_word` above) ---")
            parts.append(json.dumps(compact_seg, indent=2, ensure_ascii=False))
            if max_seg > 0 and n_seg_total > len(compact_seg):
                parts.append(
                    f"# Truncated: {len(compact_seg)} of {n_seg_total} segments "
                    f"(max_whisper_segments_in_prompt={max_seg}; 0 = all)."
                )
        return "\n".join(parts)

    # No word stream: YAML `wait_segment` only (indices match `segments` / `_load_timing` order).
    compact = prepare_whisper_segments_for_prompt(
        whisper_segments,
        max_segments=max_seg,
        max_text_chars=max_chars,
    )
    parts.append(
        "--- SEGMENT TIMING (no `words` in timing.json; YAML `wait_segment` = `whisper_index` here) ---"
    )
    parts.append(
        "# Set `wait_segment: J` on a row to wait until `segments[J].start`. "
        "When `words` exist after a later `docgen timestamps` run, prefer `wait_word` for token-level sync."
    )
    parts.append(json.dumps(compact, indent=2, ensure_ascii=False))
    if max_seg > 0 and n_seg_total > len(compact):
        parts.append(
            f"# Note: listed {len(compact)} of {n_seg_total} segments "
            f"(max_whisper_segments_in_prompt={max_seg}; 0 = all). "
            "`whisper_index` indexes the full `segments` list in timing.json."
        )
    else:
        parts.append(f"# Full segment list ({n_seg_total} segments).")

    pace_indices, pace_src = resolve_pace_segment_indices(
        num_segments=n_seg_total,
        seg_block=seg_block,
        root=root,
    )
    parts.append("")
    parts.append("--- Optional hints: beat → segment index (from docgen.yaml) ---")
    parts.append(f"# Source: {pace_src}")
    parts.append(format_pacing_schedule_markdown(whisper_segments, pace_indices))
    parts.append(
        "# Use as a coarse guide for `wait_segment` when beats line up; otherwise pick `whisper_index` from the "
        "segment JSON by matching spoken text to on-screen labels."
    )
    return "\n".join(parts)


def derive_class_name(seg_id: str, seg_name: str, override: str | None) -> str:
    """Return ``<Override>`` if provided, else ``<CamelCase(seg_name)>Scene``."""
    if override and override.strip():
        return override.strip()
    base = seg_name or seg_id
    base = re.sub(r"^\d+[-_]?", "", base)  # strip leading "08-" etc.
    parts = re.split(r"[-_\s]+", base)
    camel = "".join(p[:1].upper() + p[1:].lower() for p in parts if p)
    if not camel:
        camel = f"Segment{seg_id}"
    return f"{camel}Scene"


# ── Context collection ─────────────────────────────────────────────────────


def _resolve_repo_path(repo_root: Path, rel: str) -> Path | None:
    p = Path(rel)
    ap = (p if p.is_absolute() else (repo_root / p)).resolve()
    try:
        ap.relative_to(repo_root.resolve())
    except ValueError:
        return None
    return ap if ap.is_file() else None


def _collect_paths_from_globs(repo_root: Path, patterns: list[str]) -> list[Path]:
    found: set[Path] = set()
    rr = repo_root.resolve()
    for pat in patterns:
        pat = pat.strip()
        if not pat:
            continue
        for p in rr.glob(pat):
            if p.is_file():
                try:
                    p.resolve().relative_to(rr)
                except ValueError:
                    continue
                found.add(p.resolve())
    return sorted(found)


def collect_source_snippets(
    cfg: "Config",
    settings: SceneGenerationSettings,
    *,
    extra_paths: list[str],
) -> list[tuple[str, str]]:
    """Return ``(label, text)`` pairs respecting the configured byte budget."""
    limit = settings.max_context_bytes
    repo_root = cfg.repo_root.resolve()
    paths: list[Path] = []
    for rel in settings.context_paths + list(extra_paths):
        ap = _resolve_repo_path(repo_root, rel)
        if ap:
            paths.append(ap)
    paths.extend(_collect_paths_from_globs(repo_root, settings.context_globs))
    seen: set[Path] = set()
    ordered: list[Path] = []
    for p in paths:
        rp = p.resolve()
        if rp not in seen:
            seen.add(rp)
            ordered.append(rp)

    snippets: list[tuple[str, str]] = []
    total = 0
    per_file_cap = max(8_192, limit // max(1, len(ordered)) if ordered else limit)
    for ap in ordered:
        try:
            text = ap.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        rel_label = str(ap.relative_to(repo_root))
        if len(text) > per_file_cap:
            text = text[:per_file_cap] + "\n\n… [truncated for context budget]\n"
        if total + len(text) > limit:
            remain = limit - total
            if remain <= 100:
                break
            text = text[:remain] + "\n… [truncated]\n"
        snippets.append((rel_label, text))
        total += len(text)
        if total >= limit:
            break
    return snippets


def extract_reference_classes(scenes_py_text: str, *, max_bytes: int = 30_000) -> str:
    """Extract existing class definitions from ``scenes.py`` as few-shot examples.

    Strips the bootstrap header (palette + helpers) and returns just the
    ``class ...:`` blocks, capped to ``max_bytes`` characters total. Used to
    teach the model the project's idiomatic timing pattern without re-sending
    the helpers it must not redefine.
    """
    if not scenes_py_text.strip():
        return ""
    try:
        tree = ast.parse(scenes_py_text)
    except SyntaxError:
        return ""
    lines = scenes_py_text.splitlines(keepends=True)
    chunks: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            start = node.lineno - 1
            end = (node.end_lineno or node.lineno) if hasattr(node, "end_lineno") else node.lineno
            block = "".join(lines[start:end])
            chunks.append(block)
    out = "\n\n".join(chunks)
    if len(out) > max_bytes:
        out = out[:max_bytes] + "\n# … [reference scenes truncated for prompt budget] …\n"
    return out


# ── LLM call (OpenAI chat completions) ─────────────────────────────────────


def call_llm(*, system_prompt: str, user_message: str, model: str, temperature: float) -> str:
    """Call OpenAI chat completions; convert auth/network errors into actionable RuntimeErrors."""
    import openai

    client = openai.OpenAI()
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ],
            temperature=float(temperature),
        )
    except openai.AuthenticationError as exc:
        raise RuntimeError(
            f"OpenAI rejected OPENAI_API_KEY (authentication failed): {exc}. "
            "Set a valid key or pass --dry-run to inspect the prompt only."
        ) from exc
    except openai.PermissionDeniedError as exc:
        raise RuntimeError(
            f"OpenAI permission denied for model {model!r}: {exc}. "
            "Pick a model your account is allowed to use, or update YAML "
            "manim_scene_generation.model."
        ) from exc
    except openai.APIConnectionError as exc:
        raise RuntimeError(
            f"OpenAI connection error: {exc} — re-run when connectivity is restored."
        ) from exc
    return response.choices[0].message.content or ""


# ── Lint (compiled / hand-authored scene bodies) ───────────────────────────


_SET_OPACITY_ZERO_RE = re.compile(
    r"\.set_opacity\s*\(\s*(?:0|0\.0|0\.)\s*\)"
)

_NEXT_TO_TITLE_DOWN_LOW_BUFF_RE = re.compile(
    r"\.next_to\s*\(\s*title\b[^)]*?\bDOWN\b[^)]*?\bbuff\s*=\s*(?P<buff>0?\.\d+|0)\b",
    re.DOTALL,
)

_ANIMATE_SHIFT_UP_RE = re.compile(
    r"\.animate\.shift\s*\(\s*UP\s*\*\s*(?P<n>[0-9]*\.?[0-9]+)\s*\)"
)


def lint_animate_shift_up_collides_title(code: str) -> list[str]:
    """Reject ``<group>.animate.shift(UP * N)`` on already-placed content.

    Once a row/column has been positioned below the title (typically via
    ``_column_fit_below_title`` or ``next_to(title, DOWN, ...)``), shifting it
    UP by any meaningful amount collides with the title band. To add a new
    bottom region, anchor the **new** mobjects with ``.to_edge(DOWN, buff=0.5)``
    instead of moving existing content.
    """
    issues: list[str] = []
    for m in _ANIMATE_SHIFT_UP_RE.finditer(code):
        try:
            n = float(m.group("n"))
        except ValueError:
            continue
        if n >= 0.2:
            issues.append(
                f"layout: `.animate.shift(UP * {n})` on placed content pushes it "
                "into the title band. Anchor any NEW bottom-region content with "
                "`.to_edge(DOWN, buff=0.5)` directly; do not move existing content "
                "upward to make room."
            )
    return issues


def lint_title_down_buff_too_small(code: str) -> list[str]:
    """Catch ``.next_to(title, DOWN, buff=<0.45)`` which often collides with the title.

    Manim's ``.animate.to_edge(UP).scale(...)`` chains can leave the resolved title
    bbox larger than expected; small buffs mean the next row visibly overlaps the
    title text. ``_column_fit_below_title`` defaults to a safe buff and enforces
    a non-overlap shift; use it for grids, and ``buff >= 0.45`` for single anchors.
    """
    issues: list[str] = []
    for m in _NEXT_TO_TITLE_DOWN_LOW_BUFF_RE.finditer(code):
        try:
            value = float(m.group("buff"))
        except ValueError:
            continue
        if value < 0.45:
            issues.append(
                f"layout: `.next_to(title, DOWN, buff={value})` is too small "
                "(< 0.45); content will overlap the title band. Use "
                "`_column_fit_below_title(title, content, buff=0.55)` for grids "
                "or raise `buff >= 0.45` for single anchors."
            )
    return issues


def lint_set_opacity_then_fadein(code: str) -> list[str]:
    """Catch ``mobject.set_opacity(0)`` followed by ``FadeIn(mobject)``.

    Manim ``FadeIn`` interpolates from 0 to the mobject's *current* opacity.
    Pre-zeroing the target makes the fade end at 0 and the mobject never appears.
    Use ``self.paced_reveal(...)`` (lays out + ``FadeIn`` per Whisper start) or
    plain ``FadeIn(mobject)`` without ever calling ``set_opacity(0)`` on it.
    """
    if not _SET_OPACITY_ZERO_RE.search(code):
        return []
    if "FadeIn(" not in code:
        return []
    return [
        "anti-pattern: `.set_opacity(0)` plus later `FadeIn(...)` keeps the mobject "
        "invisible (FadeIn ends at the mobject's current opacity, which is 0). "
        "Use `self.paced_reveal(_segs, mobjects, PACE)` or call `FadeIn(mobject)` "
        "directly without `set_opacity(0)`."
    ]


def lint_generated_block(
    code: str,
    *,
    min_font_size: int = 14,
    unsafe_unicode: list[str] | None = None,
) -> list[str]:
    """Run the same checks ``docgen validate`` applies to scenes.py, scoped to ``code``.

    Returns a list of human-readable issue strings; empty means clean. The
    rules are deliberately a subset of :func:`docgen.validate._lint_manim_text_usage`
    so that anything caught here would have failed downstream validation. Run
    BEFORE writing the class into ``scenes.py`` so the file is never left in a
    state where ``docgen validate`` would fail because of LLM output.
    """
    issues: list[str] = []
    if unsafe_unicode:
        for lineno, line_text in enumerate(code.splitlines(), start=1):
            for ch in unsafe_unicode:
                if ch in line_text:
                    issues.append(
                        f"line {lineno}: unsafe unicode character "
                        f"U+{ord(ch):04X} ({ch!r}) — use ASCII equivalent"
                    )

    try:
        tree = ast.parse(code)
    except SyntaxError:
        return issues  # caller may treat parse failures separately

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        is_text = (
            (isinstance(node.func, ast.Name) and node.func.id == "Text")
            or (isinstance(node.func, ast.Attribute) and node.func.attr == "Text")
        )
        if not is_text:
            continue

        for kw in node.keywords:
            if kw.arg == "weight" and isinstance(kw.value, ast.Name) and kw.value.id == "BOLD":
                issues.append(
                    f"line {node.lineno}: Text(..., weight=BOLD) — Pango font has no bold "
                    "variant; emphasize with color/font_size instead"
                )
            if kw.arg == "font_size" and isinstance(kw.value, ast.Constant):
                val = kw.value.value
                if isinstance(val, (int, float)) and int(val) < min_font_size:
                    issues.append(
                        f"line {node.lineno}: Text() font_size={int(val)} is below "
                        f"minimum {min_font_size}; small text is unreadable in video"
                    )
    issues.extend(lint_manim_timing_stub_antipattern(tree, "generated"))
    issues.extend(lint_manim_title_down_row_collision_risk(code))
    issues.extend(lint_set_opacity_then_fadein(code))
    issues.extend(lint_title_down_buff_too_small(code))
    issues.extend(lint_animate_shift_up_collides_title(code))
    return issues


# ── Marker injection ───────────────────────────────────────────────────────


def _markers(seg_id: str, class_name: str) -> tuple[str, str]:
    return (
        MARKER_BEGIN_FMT.format(seg_id=seg_id, class_name=class_name),
        MARKER_END_FMT.format(seg_id=seg_id),
    )


def inject_or_replace(scenes_py_text: str, seg_id: str, class_name: str, class_block: str) -> str:
    """Insert ``class_block`` between marker comments, replacing any prior occurrence.

    The replacement is keyed on the ``seg_id`` end marker so the user can rename
    the class in YAML and the next regeneration still finds + replaces the
    correct block.
    """
    begin, end = _markers(seg_id, class_name)
    wrapped = f"\n\n{begin}\n{class_block.rstrip()}\n{end}\n"

    # Match either `BEGIN GENERATED SCENE: <seg_id> (...)` line followed by
    # any body up to the matching `END GENERATED SCENE: <seg_id>` line.
    pattern = re.compile(
        rf"\n*# ── BEGIN GENERATED SCENE: {re.escape(seg_id)} \([^)]*\) ──"
        rf"[\s\S]*?# ── END GENERATED SCENE: {re.escape(seg_id)} ──\n*",
        re.MULTILINE,
    )
    if pattern.search(scenes_py_text):
        return pattern.sub(wrapped, scenes_py_text)
    if not scenes_py_text.endswith("\n"):
        scenes_py_text += "\n"
    return scenes_py_text + wrapped


_AUDIO_TAIL_COMMENT = "# docgen: audio-length tail (waits through full TTS; run after `docgen timestamps`)"
# ``construct`` already waits through the last Whisper ``end`` before mass FadeOut.
_AUDIO_END_WAIT_BEFORE_FADEOUT_RE = re.compile(
    r"wait_until\s*\([\s\S]{0,1600}?max\s*\([\s\S]{0,800}?\.get\s*\(\s*[\"']end[\"']",
    re.DOTALL,
)


def append_audio_tail_to_class_body(class_body: str, timing_json_key: str) -> str:
    """Insert ``wait_until`` from last Whisper ``end`` before the final mass FadeOut.

    LLM-generated scenes typically total ~15–20s of ``timed_play`` while TTS runs
    70–120s. Without this tail, ``docgen compose`` freeze-pads the video for the
    gap and the result looks broken / ``incomplete``.  ``timing_json_key`` must
    match the stem in ``audio/<stem>.mp3`` and the top-level key in
    ``animations/timing.json`` (e.g. ``01-overview``).

    Idempotent: if :data:`_AUDIO_TAIL_COMMENT` is already present, returns
    ``class_body`` unchanged. If the model already inserted a ``wait_until`` on the
    last Whisper segment ``end`` before the mass ``FadeOut``, only the marker
    comment is inserted so ``_docgen_segs`` is not duplicated.
    """
    if _AUDIO_TAIL_COMMENT in class_body:
        return class_body
    fade_needle = "self.timed_play(*[FadeOut(m) for m in self.mobjects]"
    lines = class_body.splitlines(keepends=True)
    fade_idx: int | None = None
    for i, line in enumerate(lines):
        if fade_needle in line:
            fade_idx = i
            break
    if fade_idx is None:
        return class_body
    m = re.match(r"^(\s*)", lines[fade_idx])
    indent = m.group(1) if m else ""
    inner = f"{indent}    "
    deeper = f"{indent}        "
    prefix_before_fade = "".join(lines[:fade_idx])
    if _AUDIO_END_WAIT_BEFORE_FADEOUT_RE.search(prefix_before_fade):
        tail = f"{indent}{_AUDIO_TAIL_COMMENT}\n"
        return "".join(lines[:fade_idx] + [tail, lines[fade_idx]])
    tail = (
        f"{indent}{_AUDIO_TAIL_COMMENT}\n"
        f"{indent}_docgen_segs = _load_timing({timing_json_key!r})\n"
        f"{indent}if _docgen_segs:\n"
        f"{inner}self.wait_until(\n"
        f"{deeper}max(float(s.get(\"end\", 0.0)) for s in _docgen_segs)\n"
        f"{inner})\n"
    )
    return "".join(lines[:fade_idx] + [tail, lines[fade_idx]])


def sync_audio_tail_waits_in_scenes(cfg: "Config") -> list[str]:
    """Patch ``animations/scenes.py`` generated blocks: add audio-length tail waits.

    For each segment in ``segments.all`` whose ``visual_map`` type is ``manim``
    and whose narration audio has Whisper segments in ``timing.json``, inject
    :func:`append_audio_tail_to_class_body` into the marked block for that
    segment id.

    Returns human-readable changelog lines (empty if nothing to do).  Intended
    to run from :meth:`docgen.timestamps.TimestampExtractor.extract_all`
    immediately after ``timing.json`` is written.
    """
    scenes_path = cfg.animations_dir / "scenes.py"
    timing_path = cfg.animations_dir / "timing.json"
    if not scenes_path.is_file() or not timing_path.is_file():
        return []
    try:
        timing = json.loads(timing_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []

    text = scenes_path.read_text(encoding="utf-8")
    changes: list[str] = []

    for seg_id in cfg.segments_all:
        sid = str(seg_id)
        vm = cfg.visual_map.get(sid)
        if not isinstance(vm, dict) or str(vm.get("type", "")).lower() != "manim":
            continue
        stem = cfg.resolve_segment_name(sid)
        if not timing.get(stem, {}).get("segments"):
            continue

        block_re = re.compile(
            rf"# ── BEGIN GENERATED SCENE: {re.escape(sid)} \([^)]+\) ──\n"
            rf"[\s\S]*?"
            rf"# ── END GENERATED SCENE: {re.escape(sid)} ──",
        )
        m = block_re.search(text)
        if not m:
            continue
        block = m.group(0)
        if _AUDIO_TAIL_COMMENT in block:
            continue
        new_block = append_audio_tail_to_class_body(block, stem)
        if new_block == block:
            continue
        text = text[: m.start()] + new_block + text[m.end() :]
        changes.append(f"patched audio-length tail for segment {sid} ({stem})")

    if changes:
        scenes_path.write_text(text, encoding="utf-8")
    return changes


def ensure_scenes_bootstrap(scenes_path: Path) -> None:
    """Write ``scenes.py`` with the bootstrap header if missing or lacking helpers.

    A "lacking helpers" file is one that does not define every name in
    :data:`REQUIRED_HELPERS` at module scope. In that case we refuse to clobber
    user content and raise :class:`SceneGenerationError` so the user can fix the
    file by hand. We only write a bootstrap when the file is **missing or
    empty**.
    """
    if not scenes_path.exists() or not scenes_path.read_text(encoding="utf-8").strip():
        scenes_path.parent.mkdir(parents=True, exist_ok=True)
        scenes_path.write_text(BOOTSTRAP_HEADER, encoding="utf-8")
        return

    text = scenes_path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(text)
    except SyntaxError as exc:
        raise SceneGenerationError(
            f"{scenes_path} did not parse as Python ({exc.msg} at line {exc.lineno}). "
            "Fix the file before re-running scene-spec-generate / scene-compile."
        ) from exc

    defined: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            defined.add(node.name)
        elif isinstance(node, ast.ClassDef):
            defined.add(node.name)
    missing = [h for h in REQUIRED_HELPERS if h not in defined]
    if missing:
        raise SceneGenerationError(
            f"{scenes_path} is missing required helpers: {missing}. "
            "Either restore the helpers (palette + _box + _arrow + _load_timing + _load_timing_words + _TimedScene) "
            f"or delete {scenes_path.name} so scene-spec-generate / scene-compile can write a fresh bootstrap."
        )


# ── Narration / timing loaders (scene-spec-generate) ───────────────────────
def _load_narration(cfg: "Config", seg_id: str, seg_name: str) -> str:
    """Read ``narration/<seg_name>.md``; raise if missing (per fail-loud contract)."""
    nar_path = cfg.narration_dir / f"{seg_name}.md"
    if not nar_path.exists():
        raise SceneGenerationError(
            f"narration file not found: {nar_path}. "
            f"Run `docgen narration-generate --segment {seg_id}` first or author the file by hand."
        )
    return nar_path.read_text(encoding="utf-8")


def _load_timing_segments(cfg: "Config", seg_name: str) -> list[dict]:
    timing_path = cfg.animations_dir / "timing.json"
    if not timing_path.exists():
        return []
    try:
        data = json.loads(timing_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    return list(data.get(seg_name, {}).get("segments", []))
