"""
Manim scenes for docgen demo videos.

Pacing is driven by timing.json (generated by ``docgen timestamps``).
Scene classes below this header are authored or maintained by
``docgen scene-generate`` between marker blocks; helpers and palette are
hand-maintained.

Frame: 14.22 wide x 8 tall.  Coordinates x in [-7.11, 7.11], y in [-4, 4].
"""

from __future__ import annotations

import json
from pathlib import Path

from manim import *  # noqa: F401,F403

# ── Palette ──────────────────────────────────────────────────────────
C_BG = "#1e1e2e"
C_ACCENT = "#667eea"
C_GREEN = "#42b883"
C_ORANGE = "#f9a825"
C_BLUE = "#2979ff"
C_RED = "#ff5252"
C_TEAL = "#26c6da"
C_PURPLE = "#ce93d8"
C_WHITE = "#cdd6f4"


def _load_timing(segment_key: str) -> list[dict]:
    """Return Whisper segments from timing.json for a given segment key."""
    timing_path = Path(__file__).parent / "timing.json"
    if not timing_path.exists():
        return []
    data = json.loads(timing_path.read_text())
    return data.get(segment_key, {}).get("segments", [])


def _box(label, color, w=2.2, h=0.75, fs=18):
    r = RoundedRectangle(
        corner_radius=0.15, width=w, height=h,
        stroke_color=color, fill_color=color, fill_opacity=0.12,
    )
    t = Text(label, font_size=fs, color=color)
    return VGroup(r, t)


def _arrow(start, end, color="#cdd6f4"):
    return Arrow(start, end, color=color, stroke_width=2, buff=0.15, max_tip_length_to_length_ratio=0.12)


class _TimedScene(Scene):
    """Base with a clock that tracks elapsed scene time."""

    def setup(self):
        self._clock = 0.0

    def timed_play(self, *animations, run_time=1.0, **kwargs):
        self.play(*animations, run_time=run_time, **kwargs)
        self._clock += run_time

    def wait_until(self, target: float):
        gap = target - self._clock
        if gap > 0.05:
            self.wait(gap)
            self._clock += gap

    def timed_wait(self, duration: float):
        if duration > 0.05:
            self.wait(duration)
            self._clock += duration


# ── BEGIN GENERATED SCENE: 01 (OverviewScene) ──
class OverviewScene(_TimedScene):
    def construct(self):
        self.camera.background_color = C_BG

        seg_start, seg_end = self._clock, self._clock

        # Introduction to Docgen
        seg_start(0)
        title = Text("Docgen Overview", font_size=48, color=C_ACCENT).to_edge(UP)
        self.timed_play(Write(title), run_time=2.0)
        seg_end(0)

        # Focus on Manim and Playwright
        seg_start(1)
        manim_box = _box("Manim", C_GREEN, 3.5, 1.5, 24).shift(LEFT * 3)
        playwright_box = _box("Playwright", C_BLUE, 3.5, 1.5, 24).shift(RIGHT * 3)
        self.timed_play(FadeIn(manim_box), FadeIn(playwright_box), run_time=2.0)
        seg_end(1)

        # Command-line interface and Python library
        seg_start(2)
        cli_box = _box("CLI", C_ORANGE, 2.5, 1, 20).next_to(manim_box, DOWN, buff=1.5)
        lib_box = _box("Python Library", C_TEAL, 2.5, 1, 20).next_to(playwright_box, DOWN, buff=1.5)
        self.timed_play(FadeIn(cli_box), FadeIn(lib_box), run_time=2.0)
        seg_end(2)

        # Modern approach to video documentation
        seg_start(3)
        modern_box = _box("Modern Video Documentation", C_PURPLE, 6.5, 1.5, 24).next_to(title, DOWN, buff=1.5)
        self.timed_play(ReplacementTransform(VGroup(manim_box, playwright_box, cli_box, lib_box), modern_box), run_time=2.0)
        seg_end(3)

        # Features of Docgen
        seg_start(4)
        features_box = _box("Features", C_RED, 3, 1.5, 24).next_to(modern_box, DOWN, buff=1.5)
        self.timed_play(FadeIn(features_box), run_time=2.0)
        seg_end(4)

        # Legacy support and migration
        seg_start(5)
        legacy_box = _box("Legacy Support", C_WHITE, 3.5, 1, 20).next_to(features_box, LEFT, buff=1.5)
        migrate_box = _box("Migrate to Manim & Playwright", C_ACCENT, 5, 1, 20).next_to(features_box, RIGHT, buff=1.5)
        self.timed_play(FadeIn(legacy_box), FadeIn(migrate_box), run_time=2.0)
        seg_end(5)

        # Installation and workflows
        seg_start(6)
        install_box = _box("Installation", C_GREEN, 3, 1, 20).next_to(legacy_box, DOWN, buff=1.5)
        workflow_box = _box("Workflows", C_BLUE, 3, 1, 20).next_to(migrate_box, DOWN, buff=1.5)
        self.timed_play(FadeIn(install_box), FadeIn(workflow_box), run_time=2.0)
        seg_end(6)

        # Conclusion
        seg_start(7)
        conclusion_text = Text("Comprehensive Solution for Documentation", font_size=36, color=C_ACCENT).next_to(modern_box, DOWN, buff=2.5)
        self.timed_play(Write(conclusion_text), run_time=2.0)
        seg_end(7)

        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=1.0)
        self.timed_wait(0.5)
# ── END GENERATED SCENE: 01 ──


# ── BEGIN GENERATED SCENE: 02 (InitScaffoldScene) ──
class InitScaffoldScene(_TimedScene):
    def construct(self):
        self.camera.background_color = C_BG

        seg_start, seg_end = self._clock, self._clock

        # Introduction to init-scaffold command
        seg_start(0)
        title = Text("init-scaffold Command", font_size=48, color=C_ACCENT).to_edge(UP)
        self.timed_play(Write(title), run_time=2.0)
        seg_end(0)

        # Creating a fresh layout
        seg_start(1)
        layout_box = _box("Fresh Layout", C_GREEN, 4.5, 1.5, 24).shift(LEFT * 3)
        files_box = _box("Files & Directories", C_BLUE, 4.5, 1.5, 24).shift(RIGHT * 3)
        self.timed_play(FadeIn(layout_box), FadeIn(files_box), run_time=2.0)
        seg_end(1)

        # Generating docgen.yaml
        seg_start(2)
        yaml_box = _box("docgen.yaml", C_ORANGE, 3, 1, 20).next_to(layout_box, DOWN, buff=1.5)
        config_box = _box("Main Configuration", C_TEAL, 3, 1, 20).next_to(files_box, DOWN, buff=1.5)
        self.timed_play(FadeIn(yaml_box), FadeIn(config_box), run_time=2.0)
        seg_end(2)

        # Essential directories for assets
        seg_start(3)
        dirs_box = _box("Essential Directories", C_PURPLE, 6.5, 1.5, 24).next_to(title, DOWN, buff=1.5)
        self.timed_play(ReplacementTransform(VGroup(layout_box, files_box, yaml_box, config_box), dirs_box), run_time=2.0)
        seg_end(3)

        # Populating with content
        seg_start(4)
        content_box = _box("Add Content", C_RED, 3, 1.5, 24).next_to(dirs_box, DOWN, buff=1.5)
        self.timed_play(FadeIn(content_box), run_time=2.0)
        seg_end(4)

        # Comprehensive documentation system
        seg_start(5)
        system_box = _box("Comprehensive System", C_WHITE, 4, 1, 20).next_to(content_box, LEFT, buff=1.5)
        streamline_box = _box("Streamlined & Efficient", C_ACCENT, 5, 1, 20).next_to(content_box, RIGHT, buff=1.5)
        self.timed_play(FadeIn(system_box), FadeIn(streamline_box), run_time=2.0)
        seg_end(5)

        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=1.0)
        self.timed_wait(0.5)
# ── END GENERATED SCENE: 02 ──


# ── BEGIN GENERATED SCENE: 03 (WizardGuiScene) ──
class WizardGuiScene(_TimedScene):
    def construct(self):
        self.camera.background_color = C_BG

        seg_start, seg_end = self._clock, self._clock

        # Introduction to the wizard GUI
        seg_start(0)
        title = Text("Wizard GUI Overview", font_size=48, color=C_ACCENT).to_edge(UP)
        self.timed_play(Write(title), run_time=2.0)
        seg_end(0)

        # Streamlining narration scripts
        seg_start(1)
        streamline_box = _box("Streamline Narration Scripts", C_GREEN, 5.5, 1.5, 24).shift(UP * 1.5)
        self.timed_play(FadeIn(streamline_box), run_time=2.0)
        seg_end(1)

        # Bootstrap from documentation
        seg_start(2)
        bootstrap_box = _box("Bootstrap from Documentation", C_BLUE, 5.5, 1.5, 24).next_to(streamline_box, DOWN, buff=1.0)
        self.timed_play(FadeIn(bootstrap_box), run_time=2.0)
        seg_end(2)

        # Automate setup
        seg_start(3)
        automate_box = _box("Automate Initial Setup", C_ORANGE, 5.5, 1.5, 24).next_to(bootstrap_box, DOWN, buff=1.0)
        self.timed_play(FadeIn(automate_box), run_time=2.0)
        seg_end(3)

        # Customize narration hints
        seg_start(4)
        customize_box = _box("Customize Narration Hints", C_TEAL, 5.5, 1.5, 24).next_to(automate_box, DOWN, buff=1.0)
        self.timed_play(FadeIn(customize_box), run_time=2.0)
        seg_end(4)

        # Launch using command line
        seg_start(5)
        command_line_box = _box("Launch via Command Line", C_PURPLE, 5.5, 1.5, 24).next_to(customize_box, DOWN, buff=1.0)
        self.timed_play(FadeIn(command_line_box), run_time=2.0)
        seg_end(5)

        # Solid foundation for scripts
        seg_start(6)
        foundation_box = _box("Solid Foundation for Scripts", C_RED, 5.5, 1.5, 24).next_to(command_line_box, DOWN, buff=1.0)
        self.timed_play(FadeIn(foundation_box), run_time=2.0)
        seg_end(6)

        # Enhance productivity
        seg_start(7)
        productivity_box = _box("Enhance Productivity", C_WHITE, 5.5, 1.5, 24).next_to(foundation_box, DOWN, buff=1.0)
        self.timed_play(FadeIn(productivity_box), run_time=2.0)
        seg_end(7)

        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=1.0)
        self.timed_wait(0.5)
# ── END GENERATED SCENE: 03 ──
