"""
Manim scenes for docgen demo videos.

Pacing is driven by timing.json (generated by `docgen timestamps`).
Each scene loads its segment's Whisper timestamps and uses them
to synchronize animation beats with the spoken narration.

Frame: 14.22 wide x 8 tall.  Coordinates x in [-7.11, 7.11], y in [-4, 4].
"""

from __future__ import annotations

import json
from pathlib import Path

from manim import *

# ── Palette ──────────────────────────────────────────────────────────
C_BG = "#1e1e2e"
C_ACCENT = "#667eea"
C_GREEN = "#42b883"
C_ORANGE = "#f9a825"
C_BLUE = "#2979ff"
C_RED = "#ff5252"
C_TEAL = "#26c6da"
C_PURPLE = "#ce93d8"
C_WHITE = "#cdd6f4"


def _load_timing(segment_key: str) -> list[dict]:
    """Return Whisper segments from timing.json for a given segment key."""
    timing_path = Path(__file__).parent / "timing.json"
    if not timing_path.exists():
        return []
    data = json.loads(timing_path.read_text())
    return data.get(segment_key, {}).get("segments", [])


def _box(label, color, w=2.2, h=0.75, fs=18):
    r = RoundedRectangle(
        corner_radius=0.15, width=w, height=h,
        stroke_color=color, fill_color=color, fill_opacity=0.12,
    )
    t = Text(label, font_size=fs, color=color)
    return VGroup(r, t)


def _arrow(start, end, color=C_WHITE):
    return Arrow(start, end, color=color, stroke_width=2, buff=0.15, max_tip_length_to_length_ratio=0.12)


class _TimedScene(Scene):
    """Base with a clock that tracks elapsed scene time."""

    def setup(self):
        self._clock = 0.0

    def timed_play(self, *animations, run_time=1.0, **kwargs):
        self.play(*animations, run_time=run_time, **kwargs)
        self._clock += run_time

    def wait_until(self, target: float):
        gap = target - self._clock
        if gap > 0.05:
            self.wait(gap)
            self._clock += gap

    def timed_wait(self, duration: float):
        if duration > 0.05:
            self.wait(duration)
            self._clock += duration


# ═══════════════════════════════════════════════════════════════════════
# Scene 01 — Architecture overview  (~80s audio, 13 Whisper segments)
# ═══════════════════════════════════════════════════════════════════════

class DocgenOverviewScene(_TimedScene):
    """Animated architecture diagram showing the docgen pipeline flow.

    Whisper segment mapping:
      0-1  (0-12.9s)   Title card
      2    (12.9-19.7s) Title shrinks; inputs appear
      3    (19.7-25.8s) Config input shown
      4-6  (26.1-45.4s) Pipeline stages build up one by one
      7    (45.4-50.9s) Input arrow; single command mention
      8    (50.9-58.9s) Output row
      9-10 (59.8-70.7s) Concat + Pages
      11   (70.7-77.8s) Single command highlight
      12   (77.8-79.9s) Final beat + fade
    """

    def construct(self):
        self.camera.background_color = C_BG
        segs = _load_timing("01-overview")

        def seg_start(i: int) -> float:
            if i < len(segs):
                return segs[i]["start"]
            return self._clock

        def seg_end(i: int) -> float:
            if i < len(segs):
                return segs[i]["end"]
            return self._clock + 2

        # ── Beat 0-1: Title card ──────────────────────────────────────
        title = Text("docgen", font_size=52, color=C_ACCENT, weight=BOLD)
        subtitle = Text(
            "Markdown  →  polished demo videos",
            font_size=22, color=C_WHITE,
        )
        subtitle.next_to(title, DOWN, buff=0.3)
        title_group = VGroup(title, subtitle).move_to(ORIGIN)

        self.timed_play(Write(title), run_time=1.2)
        self.timed_play(FadeIn(subtitle, shift=UP * 0.2), run_time=0.8)

        tagline = Text(
            "Reproducible · version-controlled · fully automated",
            font_size=16, color=GREY_B,
        )
        tagline.next_to(subtitle, DOWN, buff=0.4)
        self.wait_until(seg_start(1))
        self.timed_play(FadeIn(tagline, shift=UP * 0.15), run_time=0.7)
        title_group.add(tagline)

        self.wait_until(seg_start(2))

        # ── Beat 2: Title shrinks; show inputs ────────────────────────
        self.timed_play(
            title_group.animate.scale(0.55).to_edge(UP, buff=0.3),
            run_time=0.8,
        )

        md_box = _box("Narration\n(.md)", C_GREEN, w=2.0, h=1.0, fs=16)
        md_box.move_to(LEFT * 5.5 + UP * 1.2)
        self.timed_play(FadeIn(md_box, shift=RIGHT * 0.3), run_time=0.6)

        # ── Beat 3: Config input ──────────────────────────────────────
        self.wait_until(seg_start(3))
        yaml_box = _box("docgen.yaml", C_ORANGE, w=2.0, h=0.7, fs=15)
        yaml_box.move_to(LEFT * 5.5 + DOWN * 0.3)
        self.timed_play(FadeIn(yaml_box, shift=RIGHT * 0.3), run_time=0.5)
        self.wait_until(seg_start(4))

        # ── Beats 4-6: Pipeline stages ────────────────────────────────
        stages = [
            ("TTS", C_PURPLE, "OpenAI\ngpt-4o-mini-tts"),
            ("Manim", C_TEAL, "Animations"),
            ("VHS", C_GREEN, "Terminal\nrecordings"),
            ("Compose", C_BLUE, "ffmpeg"),
            ("Validate", C_RED, "Drift / lint"),
        ]

        stage_boxes = []
        x_start = -3.0
        x_gap = 2.0
        for i, (label, color, desc) in enumerate(stages):
            box = _box(label, color, w=1.7, h=0.7, fs=15)
            box.move_to(RIGHT * (x_start + i * x_gap) + UP * 1.2)
            desc_text = Text(desc, font_size=11, color=color).next_to(box, DOWN, buff=0.15)
            stage_boxes.append(VGroup(box, desc_text))

        stage_span = seg_end(6) - seg_start(4)
        per_stage = max(0.4, stage_span / (len(stages) * 2))

        for i, sb in enumerate(stage_boxes):
            self.timed_play(FadeIn(sb, shift=DOWN * 0.2), run_time=per_stage)
            if i < len(stage_boxes) - 1:
                arr = _arrow(
                    sb[0].get_right(),
                    stage_boxes[i + 1][0].get_left(),
                    color=C_WHITE,
                )
                self.timed_play(Create(arr), run_time=per_stage * 0.6)

        # ── Beat 7: Input arrow + single command ──────────────────────
        self.wait_until(seg_start(7))
        input_arr = _arrow(md_box.get_right(), stage_boxes[0][0].get_left(), color=C_GREEN)
        self.timed_play(Create(input_arr), run_time=0.5)
        self.wait_until(seg_start(8))

        # ── Beat 8: Output row ────────────────────────────────────────
        outputs_label = Text("Outputs", font_size=18, color=C_ACCENT)
        outputs_label.move_to(DOWN * 1.5 + LEFT * 5)

        out_items = [
            ("audio/*.mp3", C_PURPLE),
            ("recordings/*.mp4", C_BLUE),
            ("full-demo.mp4", C_ACCENT),
            ("index.html", C_TEAL),
        ]
        out_group = VGroup()
        for j, (olabel, ocolor) in enumerate(out_items):
            ot = Text(olabel, font_size=14, color=ocolor)
            ot.move_to(RIGHT * (-3.0 + j * 2.8) + DOWN * 1.5)
            out_group.add(ot)

        self.timed_play(FadeIn(outputs_label), run_time=0.4)

        out_per = max(0.3, (seg_start(9) - self._clock - 1.0) / len(out_group))
        for o in out_group:
            self.timed_play(FadeIn(o, shift=UP * 0.15), run_time=out_per)

        output_arrows = VGroup()
        for sb in [stage_boxes[-1]]:
            arr = _arrow(sb[0].get_bottom(), outputs_label.get_top(), color=C_ACCENT)
            output_arrows.add(arr)
        self.timed_play(Create(output_arrows[0]), run_time=0.5)

        self.wait_until(seg_start(9))

        # ── Beats 9-10: Concat + Pages ────────────────────────────────
        concat_box = _box("Concat", C_ACCENT, w=1.6, h=0.6, fs=15)
        concat_box.move_to(RIGHT * 4.5 + DOWN * 0.5)
        pages_box = _box("Pages", C_TEAL, w=1.6, h=0.6, fs=15)
        pages_box.move_to(RIGHT * 4.5 + DOWN * 1.5)

        val_to_concat = _arrow(
            stage_boxes[-1][0].get_right() + DOWN * 0.1,
            concat_box.get_left(),
            color=C_ACCENT,
        )
        concat_to_pages = _arrow(
            concat_box.get_bottom(), pages_box.get_top(), color=C_TEAL,
        )

        self.timed_play(Create(val_to_concat), FadeIn(concat_box), run_time=0.5)
        self.timed_play(Create(concat_to_pages), FadeIn(pages_box), run_time=0.5)

        checks_group = VGroup()
        check_items = [
            ("✓ stream presence", C_GREEN),
            ("✓ A/V drift < 2.75s", C_GREEN),
            ("✓ no blank frames", C_GREEN),
            ("✓ narration lint clean", C_GREEN),
        ]
        for ci, (cl, cc) in enumerate(check_items):
            ct = Text(cl, font_size=12, color=cc)
            ct.move_to(LEFT * 5.0 + DOWN * (1.8 + ci * 0.35))
            checks_group.add(ct)

        check_per = max(0.3, (seg_start(11) - self._clock - 0.5) / len(check_items))
        for ct in checks_group:
            self.timed_play(FadeIn(ct, shift=RIGHT * 0.2), run_time=check_per)

        self.wait_until(seg_start(11))

        # ── Beat 11: Single command highlight ─────────────────────────
        cmd = Text(
            "docgen generate-all",
            font_size=24, color=C_ACCENT, weight=BOLD,
        )
        cmd_bg = RoundedRectangle(
            corner_radius=0.12, width=cmd.width + 0.6, height=cmd.height + 0.4,
            stroke_color=C_ACCENT, fill_color=C_BG, fill_opacity=0.9,
        )
        cmd_group = VGroup(cmd_bg, cmd).move_to(DOWN * 3.0)

        self.timed_play(FadeIn(cmd_group, shift=UP * 0.3), run_time=0.7)
        self.timed_play(Indicate(cmd_group, color=C_ACCENT, scale_factor=1.05), run_time=0.8)

        config_items = VGroup()
        cfg_entries = [
            ("segments:", C_ACCENT),
            ("  visual_map:", C_TEAL),
            ("  tts:", C_PURPLE),
            ("  validation:", C_RED),
            ("  wizard:", C_ORANGE),
        ]
        for ci, (cl, cc) in enumerate(cfg_entries):
            ct = Text(cl, font_size=12, color=cc, font="Monospace")
            ct.move_to(RIGHT * 4.0 + DOWN * (1.8 + ci * 0.3))
            config_items.add(ct)

        cfg_label = Text("docgen.yaml", font_size=14, color=C_ORANGE, weight=BOLD)
        cfg_label.move_to(RIGHT * 4.0 + DOWN * 1.4)
        self.timed_play(FadeIn(cfg_label), run_time=0.3)

        cfg_per = max(0.2, (seg_start(12) - self._clock - 0.3) / len(config_items))
        for ct in config_items:
            self.timed_play(FadeIn(ct, shift=RIGHT * 0.15), run_time=cfg_per)

        self.wait_until(seg_start(12))

        # ── Beat 12: Final + fade out ─────────────────────────────────
        self.wait_until(seg_end(12) - 1.5)
        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=1.0)
        self.timed_wait(0.5)


# ═══════════════════════════════════════════════════════════════════════
# Scene 03 — Wizard GUI walkthrough  (~77.5s audio, 17 Whisper segments)
# ═══════════════════════════════════════════════════════════════════════

class WizardGUIScene(_TimedScene):
    """Animated walkthrough of the docgen wizard web interface.

    Whisper segment mapping:
      0    (0-5.9s)     Title card
      1    (6.9-10.6s)  Browser frame + URL bar
      2    (10.9-14.9s) Tab bar
      3-4  (15.3-21.0s) Setup view: file tree
      5    (21.8-25.2s) Checkboxes
      6-7  (25.9-35.3s) Dwell on setup
      8    (36.2-39.9s) Switch to Production tab
      9    (40.8-42.7s) Segment list
      10   (43.2-48.3s) Editor panel
      11   (48.9-55.0s) Editor text content
      12   (55.4-59.3s) Save/Approve buttons
      13   (60.0-64.1s) Click approve animation
      14   (64.8-68.7s) Progress bar
      15   (69.0-73.4s) State file callout
      16   (73.4-77.5s) Final dwell + fade
    """

    def construct(self):
        self.camera.background_color = C_BG
        segs = _load_timing("03-wizard-gui")

        def seg_start(i: int) -> float:
            if i < len(segs):
                return segs[i]["start"]
            return self._clock

        def seg_end(i: int) -> float:
            if i < len(segs):
                return segs[i]["end"]
            return self._clock + 2

        # ── Beat 0: Title ─────────────────────────────────────────────
        title = Text("docgen wizard", font_size=44, color=C_ACCENT, weight=BOLD)
        subtitle = Text(
            "Local web GUI for narration authoring",
            font_size=20, color=C_WHITE,
        )
        subtitle.next_to(title, DOWN, buff=0.25)
        tg = VGroup(title, subtitle).move_to(ORIGIN)

        self.timed_play(Write(title), run_time=0.8)
        self.timed_play(FadeIn(subtitle, shift=UP * 0.2), run_time=0.6)
        self.wait_until(seg_start(1))
        self.timed_play(tg.animate.scale(0.5).to_edge(UP, buff=0.25), run_time=0.7)

        # ── Beat 1: Browser frame ────────────────────────────────────
        browser = RoundedRectangle(
            corner_radius=0.15, width=11, height=5.8,
            stroke_color=C_WHITE, stroke_width=1.5,
            fill_color="#11111b", fill_opacity=0.6,
        )
        browser.move_to(DOWN * 0.5)

        url_bar = RoundedRectangle(
            corner_radius=0.08, width=6, height=0.35,
            stroke_color=GREY_D, fill_color="#181825", fill_opacity=0.8,
        )
        url_bar.move_to(browser.get_top() + DOWN * 0.4)
        url_text = Text(
            "localhost:8501", font_size=12, color=GREY_B,
        ).move_to(url_bar)

        self.timed_play(FadeIn(browser), FadeIn(url_bar), FadeIn(url_text), run_time=0.6)
        self.wait_until(seg_start(2))

        # ── Beat 2: Tab bar ──────────────────────────────────────────
        tab_y = browser.get_top()[1] - 0.85
        setup_tab = self._tab("Setup", C_ACCENT, active=True)
        setup_tab.move_to(LEFT * 1.5 + UP * tab_y)
        prod_tab = self._tab("Production", C_WHITE, active=False)
        prod_tab.move_to(RIGHT * 1.5 + UP * tab_y)

        self.timed_play(FadeIn(setup_tab), FadeIn(prod_tab), run_time=0.5)
        self.wait_until(seg_start(3))

        # ── Beats 3-4: Setup view file tree ──────────────────────────
        tree_title = Text("Repository files", font_size=14, color=C_ACCENT)
        tree_title.move_to(LEFT * 3.5 + UP * 1.0)

        files = [
            ("  src/", C_GREEN),
            ("    docgen/cli.py", C_WHITE),
            ("    docgen/tts.py", C_WHITE),
            ("    docgen/compose.py", C_WHITE),
            ("  tests/", C_GREEN),
            ("    test_init.py", C_WHITE),
            ("  README.md", C_WHITE),
            ("  pyproject.toml", C_ORANGE),
        ]
        file_items = VGroup()
        for i, (fname, fcolor) in enumerate(files):
            ft = Text(fname, font_size=11, color=fcolor, font="Monospace")
            ft.move_to(LEFT * 3.5 + UP * (0.5 - i * 0.3))
            file_items.add(ft)

        self.timed_play(FadeIn(tree_title), run_time=0.3)
        self.timed_play(
            *[FadeIn(f, shift=RIGHT * 0.1) for f in file_items],
            run_time=0.6,
        )
        self.wait_until(seg_start(5))

        # ── Beat 5: Checkboxes ───────────────────────────────────────
        checks = VGroup()
        for i in range(len(files)):
            check = Text("☑", font_size=12, color=C_GREEN)
            check.move_to(LEFT * 5.0 + UP * (0.5 - i * 0.3))
            checks.add(check)

        self.timed_play(
            *[FadeIn(c, shift=LEFT * 0.1) for c in checks],
            run_time=0.5,
        )
        self.wait_until(seg_start(6))

        # ── Beats 6-7: Exclude patterns filter animation ─────────
        exclude_title = Text("Excluded by docgen.yaml:", font_size=13, color=C_ORANGE)
        exclude_title.move_to(RIGHT * 2.5 + UP * 0.8)

        excluded_dirs = [
            "node_modules/",
            "__pycache__/",
            ".pytest_cache/",
            ".venv/",
        ]
        excl_group = VGroup()
        for ei, edir in enumerate(excluded_dirs):
            et = Text(edir, font_size=11, color=C_RED, font="Monospace")
            cross = Text("✗", font_size=13, color=C_RED)
            et.move_to(RIGHT * 3.0 + UP * (0.3 - ei * 0.35))
            cross.move_to(RIGHT * 1.8 + UP * (0.3 - ei * 0.35))
            excl_group.add(VGroup(cross, et))

        self.timed_play(FadeIn(exclude_title), run_time=0.4)

        excl_per = max(0.3, (seg_start(8) - self._clock - 0.5) / len(excl_group))
        for eg in excl_group:
            self.timed_play(FadeIn(eg, shift=LEFT * 0.15), run_time=excl_per)

        self.wait_until(seg_start(8) - 0.3)
        self.timed_play(
            FadeOut(exclude_title), FadeOut(excl_group), run_time=0.3,
        )
        self.wait_until(seg_start(8))

        # ── Beat 8: Switch to Production tab ─────────────────────────
        new_setup = self._tab("Setup", C_WHITE, active=False)
        new_setup.move_to(setup_tab.get_center())
        new_prod = self._tab("Production", C_ACCENT, active=True)
        new_prod.move_to(prod_tab.get_center())

        self.timed_play(
            FadeOut(tree_title), FadeOut(file_items), FadeOut(checks),
            ReplacementTransform(setup_tab, new_setup),
            ReplacementTransform(prod_tab, new_prod),
            run_time=0.6,
        )

        # ── Beat 9: Segment list (immediately after tab switch) ──────
        segments = [
            ("01-overview", "approved", C_GREEN),
            ("02-init-scaffold", "approved", C_GREEN),
            ("03-wizard-gui", "editing", C_ORANGE),
            ("04-tts-pipeline", "draft", C_PURPLE),
            ("05-compose-validate", "pending", GREY_B),
            ("06-ci-integration", "pending", GREY_B),
        ]

        seg_list = VGroup()
        for i, (sname, status, scolor) in enumerate(segments):
            row = VGroup()
            name_t = Text(sname, font_size=13, color=C_WHITE)
            name_t.move_to(LEFT * 3.5 + UP * (0.8 - i * 0.45))
            status_t = Text(status, font_size=11, color=scolor)
            status_t.move_to(LEFT * 1.0 + UP * (0.8 - i * 0.45))
            dot = Dot(color=scolor, radius=0.06)
            dot.move_to(LEFT * 1.8 + UP * (0.8 - i * 0.45))
            row.add(name_t, dot, status_t)
            seg_list.add(row)

        self.timed_play(
            *[FadeIn(s, shift=RIGHT * 0.1) for s in seg_list],
            run_time=0.7,
        )
        self.wait_until(seg_start(10))

        # ── Beat 10-11: Editor panel ─────────────────────────────────
        editor_bg = RoundedRectangle(
            corner_radius=0.1, width=4.5, height=3.5,
            stroke_color=GREY_D, fill_color="#181825", fill_opacity=0.8,
        )
        editor_bg.move_to(RIGHT * 3.0 + DOWN * 0.4)

        editor_title = Text("03-wizard-gui.md", font_size=12, color=C_ACCENT)
        editor_title.move_to(editor_bg.get_top() + DOWN * 0.25)

        self.timed_play(FadeIn(editor_bg), FadeIn(editor_title), run_time=0.5)
        self.wait_until(seg_start(11))

        editor_lines = [
            "The wizard is a local web",
            "GUI that helps you draft",
            "narration scripts from your",
            "existing project docs.",
            " ",
            "Run docgen wizard and it",
            "launches a Flask server...",
        ]
        editor_text = VGroup()
        left_edge = editor_bg.get_left()[0] + 0.3
        for i, line in enumerate(editor_lines):
            lt = Text(line, font_size=10, color=C_WHITE, font="Monospace")
            lt.move_to(np.array([left_edge + lt.width / 2, 0.3 - i * 0.25, 0]))
            editor_text.add(lt)

        self.timed_play(
            *[FadeIn(lt) for lt in editor_text],
            run_time=0.6,
        )
        self.wait_until(seg_start(12))

        # ── Beat 12: Save / Approve buttons ──────────────────────────
        save_btn = self._button("Save", C_GREEN)
        save_btn.move_to(RIGHT * 2.2 + DOWN * 1.9)
        approve_btn = self._button("Approve", C_ACCENT)
        approve_btn.move_to(RIGHT * 3.8 + DOWN * 1.9)

        self.timed_play(FadeIn(save_btn), FadeIn(approve_btn), run_time=0.4)
        self.wait_until(seg_start(13))

        # ── Beat 13: Click approve ───────────────────────────────────
        self.timed_play(
            Indicate(approve_btn, color=C_ACCENT, scale_factor=1.1),
            run_time=0.5,
        )
        self.wait_until(seg_start(14))

        # ── Beat 14: Progress bar ────────────────────────────────────
        prog_bg = RoundedRectangle(
            corner_radius=0.08, width=8, height=0.3,
            stroke_color=GREY_D, fill_color="#181825", fill_opacity=0.6,
        )
        prog_bg.move_to(DOWN * 2.8)
        prog_fill = RoundedRectangle(
            corner_radius=0.08, width=4.0, height=0.3,
            stroke_color=C_GREEN, fill_color=C_GREEN, fill_opacity=0.3,
        )
        prog_fill.align_to(prog_bg, LEFT)
        prog_label = Text("3 / 6 approved", font_size=11, color=C_GREEN)
        prog_label.next_to(prog_bg, RIGHT, buff=0.2)

        self.timed_play(FadeIn(prog_bg), GrowFromEdge(prog_fill, LEFT), FadeIn(prog_label), run_time=0.8)
        self.wait_until(seg_start(15))

        # ── Beat 15: State file callout ──────────────────────────────
        state_text = Text(
            ".docgen-state.json", font_size=13, color=C_ORANGE,
        )
        state_text.move_to(DOWN * 3.5)
        state_note = Text(
            "Tracks progress · excluded from git",
            font_size=10, color=GREY_B,
        )
        state_note.next_to(state_text, RIGHT, buff=0.3)

        self.timed_play(FadeIn(state_text), FadeIn(state_note), run_time=0.5)
        self.wait_until(seg_start(16))

        # ── Beat 16: Final dwell + fade ──────────────────────────────
        self.wait_until(seg_end(16) - 1.5)
        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=1.0)
        self.timed_wait(0.5)

    @staticmethod
    def _tab(label, color, active=False):
        t = Text(label, font_size=15, color=color, weight=BOLD if active else NORMAL)
        underline = Line(
            t.get_left() + DOWN * 0.15,
            t.get_right() + DOWN * 0.15,
            color=color if active else "#11111b",
            stroke_width=2,
        )
        return VGroup(t, underline)

    @staticmethod
    def _button(label, color):
        t = Text(label, font_size=12, color=color)
        r = RoundedRectangle(
            corner_radius=0.08, width=t.width + 0.4, height=t.height + 0.25,
            stroke_color=color, fill_color=color, fill_opacity=0.1,
        )
        return VGroup(r, t)
